---
dist: bionic

language: python

env:
  - VAGRANT_VERSION="2.2.7" VIRTUALBOX_VERSION="6.1"

before_install:
  - source /etc/os-release
  - sudo apt-get update
  - sudo apt-get install -y apt-transport-https gnupg2 software-properties-common wget bridge-utils dnsmasq-base ebtables libvirt-bin libvirt-dev qemu-kvm qemu-utils ruby-dev
  - wget https://releases.hashicorp.com/vagrant/${VAGRANT_VERSION}/vagrant_${VAGRANT_VERSION}_x86_64.deb
  - sudo apt-get install -y ./vagrant_${VAGRANT_VERSION}_x86_64.deb
  - curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
  - sudo apt-get update
  - sudo apt-get install -y kubectl
  - sudo vagrant plugin install vagrant-libvirt

script:
  - sudo vagrant up --provider=libvirt
  - export KUBECONFIG=$KUBECONFIG:~/.kube/vagrant-k8s.yml
  - kubectl get all --all-namespaces
  - ./scripts/cleanup.sh
