---
- src: https://github.com/mrlesmithjr/ansible-change-hostname.git
- src: https://github.com/mrlesmithjr/ansible-docker.git
- src: https://github.com/mrlesmithjr/ansible-etc-hosts.git
- src: https://github.com/mrlesmithjr/ansible-k8s.git
- src: https://github.com/mrlesmithjr/ansible-nfs-client.git
- src: https://github.com/mrlesmithjr/ansible-nfs-server.git
- src: https://github.com/mrlesmithjr/ansible-ntp.git
- src: https://github.com/mrlesmithjr/ansible-timezone.git
