---
- name: redhat | Uninstalling Old Docker Package (if exists)
  package:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-engine
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
    state: absent
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | Uninstalling Old Docker Package (if exists)
  package:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-engine
      - docker-engine-selinux
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
    state: absent
  become: true
  register: result
  until: result is successful
  when: ansible_distribution == "Fedora"

- name: redhat | adding Docker repo
  template:
    src: etc/yum.repos.d/docker.repo.j2
    dest: /etc/yum.repos.d/docker.repo
  become: true

- name: redhat | installing Docker
  package:
    name:
      - "docker-ce-{{ docker_version_redhat }}"
      - containerd.io
    state: present
  become: true
  register: result
  until: result is successful
