---
galaxy_info:
  author: Larry Smith Jr.
  description: Ansible role to install/configure NTP
  license: MIT
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Fedora
      versions:
        - 24
        - 25
        - 26
        - 27
        - 28
        - 29
    - name: Ubuntu
      versions:
        - bionic
        - precise
        - trusty
        - xenial
    - name: Debian
      versions:
        - jessie
        - stretch
        - wheezy
  galaxy_tags:
    - networking
    - system

dependencies: []
